ALTER TABLE recipetuner_subscription_plans
ADD COLUMN IF NOT EXISTS price DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS interval_type VARCHAR(20) DEFAULT 'month',
ADD COLUMN IF NOT EXISTS max_recipes INTEGER DEFAULT 3,
ADD COLUMN IF NOT EXISTS ai_features BOOLEAN DEFAULT false;